---
preprocessing:
  min_symbols: 2
  min_words: 3
  stopwords: True
fasttext:
  init:
    window: 5
    vector_size: 100
    min_count: 5
    negative: 10
    seed: 7
  train:
    epochs: 40
umap:
  n_components: 3
  metric: cosine
  random_state: 7
  n_neighbors: 15
clusters:
  hdbscan:
    min_cluster_size: 10
    min_samples: 15
    metric: euclidean
  dbscan:
    eps: 0.5
    min_samples: 20
  agglomerative:
    n_clusters: null
    distance_threshold: 25
    linkage: ward
  spectral:
    affinity: nearest_neighbors
    n_neighbors: 20
    assign_labels: discretize
    random_state: 7
  kmeans:
    random_state: 7
  n_minmax:
      - 2
      - 30
wordcloud:
  background_color: white
  max_words: 100
  width: 800
  height: 400
  min_font_size: 6
  colormap: nipy_spectral
  random_state: 7
...